import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Noto_Sans_KR, Roboto } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

const notoSansKR = Noto_Sans_KR({ subsets: ["latin"], variable: "--font-noto-kr" });
const roboto = Roboto({ weight: "400", variable: "--font-roboto" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={cn("min-h-screen antialiased font-baseFont", notoSansKR.variable, roboto.variable)}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
