// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function StartServer(arg1:number):Promise<string>;

export function Status():Promise<main.ServerStatus>;

export function StopServer():Promise<void>;
